### ISSUE TITLE
Use cretz/tor-static instead of go-libtor

### ISSUE THREAD

**Issue by lu4p** [ciehanski/onionbox#9]
This would add support for windows and potentially faster conpile times https://github.com/cretz/tor-static

**Comment by lu4p** [comment]
See how to build here
https://github.com/lu4p/ToRAT/wiki/Setup#client-with-embedded-tor

**Comment by lu4p** [comment]
How to use in code:
https://github.com/lu4p/ToRat_client/blob/master/client/netclient.go

**Comment by ciehanski** [comment]
Currently looking into this. Thank you for sharing!

**Comment by ciehanski** [comment]
Will not be switching to cretz/tor-static at this time.
